### ISSUE TITLE
[1.12.2] [1.0.1] Inventory bug with crafting table

### ISSUE THREAD

**Issue by wamc2017** [V0idWa1k3r/ExPetrum#2]
If some item (a tool for an instance) is left in the crafting table and there's normally no space in the inventory for the item, the item is still picked up...

![inventory](https://user-images.githubusercontent.com/33242447/42687257-9e135fea-8698-11e8-9c97-41cd5047e2cd.png)

Thanks for looking into it.

**Comment by V0idWa1k3r** [comment]
That actually is a vanilla "bug". Vanilla simply adds the items left in the crafting grid to the inventory without checking whether the slots can accept the item or not. I believe that is something recently added to vanilla as it used to just drop items on the ground. In any case there really isn't a way for me to fix that since there isn't a "item added to inventory" event and vanilla is bypassing my slot wrappers. Most I could do is periodically check whether the items are allowed to be in the slots and if not - drop them from the player's inventory. Would this be an acceptable solution or would that be too annoying to deal with?

**Comment by wamc2017** [comment]
For me it's fine, if the item is dropped.
